######################################################################
# Automatically generated by qmake (3.1) Thu Aug 28 18:13:29 2025
######################################################################

TEMPLATE = subdirs

# Directories
CONFIG += console 
QT += core widgets network websockets multimedia multimediawidgets 
TARGET = test_error_integration 
INCLUDEPATH += ../include 
SOURCES += ../test_error_handling_integration.cpp 
SOURCES += ../src/JitsiError.cpp 
SOURCES += ../src/ErrorRecoveryManager.cpp 
SOURCES += ../src/ErrorDialog.cpp 
SOURCES += ../src/ErrorUtils.cpp 
HEADERS += ../include/JitsiError.h 
HEADERS += ../include/ErrorRecoveryManager.h 
HEADERS += ../include/ErrorDialog.h 
HEADERS += ../include/ErrorUtils.h 
HEADERS += ../include/JitsiConstants.h 
